// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9NvsqPuoa6BBOcGXwnYMfaC5VqsuLCck',
    appId: '1:508838894460:web:6a36552c40c300bb3de2f9',
    messagingSenderId: '508838894460',
    projectId: 'rentit-30415',
    authDomain: 'rentit-30415.firebaseapp.com',
    storageBucket: 'rentit-30415.firebasestorage.app',
    measurementId: 'G-PRJGJFMH41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-inF38lHfpxkNrSpi6MYA5-ttqpMBo5k',
    appId: '1:508838894460:android:15e9f41937806ccf3de2f9',
    messagingSenderId: '508838894460',
    projectId: 'rentit-30415',
    storageBucket: 'rentit-30415.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBml2X5j-WSwGEIUB4SzQc4WYbHxs6qrYM',
    appId: '1:508838894460:ios:bc29c13d7d0fa22d3de2f9',
    messagingSenderId: '508838894460',
    projectId: 'rentit-30415',
    storageBucket: 'rentit-30415.firebasestorage.app',
    iosBundleId: 'com.example.rentit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBml2X5j-WSwGEIUB4SzQc4WYbHxs6qrYM',
    appId: '1:508838894460:ios:bc29c13d7d0fa22d3de2f9',
    messagingSenderId: '508838894460',
    projectId: 'rentit-30415',
    storageBucket: 'rentit-30415.firebasestorage.app',
    iosBundleId: 'com.example.rentit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9NvsqPuoa6BBOcGXwnYMfaC5VqsuLCck',
    appId: '1:508838894460:web:a05253b13ce667643de2f9',
    messagingSenderId: '508838894460',
    projectId: 'rentit-30415',
    authDomain: 'rentit-30415.firebaseapp.com',
    storageBucket: 'rentit-30415.firebasestorage.app',
    measurementId: 'G-2K8SY17CJS',
  );
}
