import 'package:flutter/material.dart';

final List<Map<String, dynamic>> kCatalogCategories = [
  {'key': 'ALL', 'labelFr': 'Tous', 'labelEn': 'All', 'icon': Icons.grid_view_rounded},
  {'key': 'TOOLS', 'labelFr': 'Outillage', 'labelEn': 'Tools', 'icon': Icons.construction_rounded},
  {'key': 'PHOTO', 'labelFr': 'Photo & Vidéo', 'labelEn': 'Photo & Video', 'icon': Icons.camera_alt_outlined},
  {'key': 'AUDIO', 'labelFr': 'Sonorisation', 'labelEn': 'Audio & Sound', 'icon': Icons.speaker_outlined},
  {'key': 'OUTDOOR', 'labelFr': 'Plein air', 'labelEn': 'Outdoors', 'icon': Icons.terrain_outlined},
];

final List<Map<String, dynamic>> kCatalogItems = [
  {
    'id': 'item_1',
    'name': 'Perceuse à percussion sans fil 18V',
    'nameFr': 'Perceuse à percussion sans fil 18V',
    'nameEn': '18V Cordless Hammer Drill',
    'category': 'TOOLS',
    'categoryFr': 'Outillage',
    'categoryEn': 'Tools',
    'city': 'Paris, France',
    'price': 25,
    'rating': 4.8,
    'reviews': 34,
    'color': const Color(0xFFEFF6FF),
    'icon': Icons.construction,
    'iconColor': const Color(0xFF2563EB),
    'image': 'assets/images/drill.jpg',
    'images': [
      'assets/images/drill.jpg',
      'assets/images/bosch_drill.jpg',
      'assets/images/drill3.jpg',
    ],
    'isAvailable': true,
    'descFr': 'Perceuse à percussion professionnelle 18V avec deux batteries Lithium-ion 4.0Ah et mandrin métallique 13mm.',
    'descEn': 'Professional 18V hammer drill with two 4.0Ah Lithium-ion batteries and 13mm heavy-duty keyless chuck.',
  },
  {
    'id': 'item_2',
    'name': 'Appareil photo Cinema 4K Pro',
    'nameFr': 'Appareil photo Cinema 4K Pro',
    'nameEn': 'Cinema 4K Pro Camera',
    'category': 'PHOTO',
    'categoryFr': 'Photo & Vidéo',
    'categoryEn': 'Photography',
    'city': 'Paris, France',
    'price': 45,
    'rating': 4.9,
    'reviews': 28,
    'color': const Color(0xFFF5F3FF),
    'icon': Icons.camera_alt_outlined,
    'iconColor': const Color(0xFF7C3AED),
    'image': 'assets/images/camera.jpg',
    'images': [
      'assets/images/camera.jpg',
      'assets/images/camera2.jpg',
      'assets/images/lens.jpg',
    ],
    'isAvailable': true,
    'descFr': 'Caméra plein format 4K 120fps avec profil LOG, stabilisateur 5 axes et monture interchangeable.',
    'descEn': 'Full-frame 4K 120fps camera with LOG profiles, 5-axis IBIS, and interchangeable lens mount.',
  },
  {
    'id': 'item_3',
    'name': 'Brise-béton professionnel 1600W',
    'nameFr': 'Brise-béton professionnel 1600W',
    'nameEn': '1600W Demolition Breaker Hammer',
    'category': 'TOOLS',
    'categoryFr': 'Outillage',
    'categoryEn': 'Tools',
    'city': 'Lomé, Togo',
    'price': 40,
    'rating': 4.7,
    'reviews': 19,
    'color': const Color(0xFFFEF2F2),
    'icon': Icons.hardware_outlined,
    'iconColor': const Color(0xFFEF4444),
    'image': 'assets/images/jackhammer.jpg',
    'images': [
      'assets/images/jackhammer.jpg',
      'assets/images/jackhammer2.jpg',
      'assets/images/abbruchhammer.jpg',
    ],
    'isAvailable': true,
    'descFr': 'Marteau piqueur brise-béton 1600W à force d\'impact de 45 Joules, fourni avec burin plat et pointe conique.',
    'descEn': 'Heavy-duty 1600W demolition breaker with 45J impact energy, supplied with flat chisel and bull point.',
  },
  {
    'id': 'item_4',
    'name': 'Boîte à outils complète 120 pièces',
    'nameFr': 'Boîte à outils complète 120 pièces',
    'nameEn': '120-Piece Complete Tool Kit',
    'category': 'TOOLS',
    'categoryFr': 'Outillage',
    'categoryEn': 'Tools',
    'city': 'Cotonou, Bénin',
    'price': 15,
    'rating': 4.8,
    'reviews': 42,
    'color': const Color(0xFFFFFBEB),
    'icon': Icons.handyman_outlined,
    'iconColor': const Color(0xFFF59E0B),
    'image': 'assets/images/toolkit.jpg',
    'images': [
      'assets/images/toolkit.jpg',
      'assets/images/toolkit2.jpg',
      'assets/images/socket_set.jpg',
    ],
    'isAvailable': true,
    'descFr': 'Coffret atelier complet en chrome vanadium avec cliquets, douilles métriques, pinces et clés mixtes.',
    'descEn': 'Chrome vanadium mechanic set with quick-release ratchets, metric sockets, pliers, and combination wrenches.',
  },
  {
    'id': 'item_5',
    'name': 'Tente de camping 4 personnes',
    'nameFr': 'Tente de camping 4 personnes',
    'nameEn': '4-Person Camping Tent',
    'category': 'OUTDOOR',
    'categoryFr': 'Plein air',
    'categoryEn': 'Outdoors',
    'city': 'Abidjan, Côte d\'Ivoire',
    'price': 30,
    'rating': 4.6,
    'reviews': 15,
    'color': const Color(0xFFECFDF5),
    'icon': Icons.terrain_outlined,
    'iconColor': const Color(0xFF059669),
    'image': 'assets/images/tent.jpg',
    'images': [
      'assets/images/tent.jpg',
      'assets/images/tent2.jpg',
      'assets/images/tent3.jpg',
    ],
    'isAvailable': true,
    'descFr': 'Tente familiale dôme 4 places avec double toit imperméable 3000mm et moustiquaires intégrées.',
    'descEn': 'Spacious 4-person dome tent featuring 3000mm waterproof rainfly and high-density anti-bug mesh panels.',
  },
  {
    'id': 'item_6',
    'name': 'Vélo tout-terrain aluminium',
    'nameFr': 'Vélo tout-terrain aluminium',
    'nameEn': 'Aluminum Mountain Bike (MTB)',
    'category': 'OUTDOOR',
    'categoryFr': 'Plein air',
    'categoryEn': 'Outdoors',
    'city': 'Dakar, Sénégal',
    'price': 20,
    'rating': 4.7,
    'reviews': 22,
    'color': const Color(0xFFEFF6FF),
    'icon': Icons.directions_bike_outlined,
    'iconColor': const Color(0xFF2563EB),
    'image': 'assets/images/bike.jpg',
    'images': [
      'assets/images/bike.jpg',
      'assets/images/bike2.jpg',
      'assets/images/bike3.jpg',
    ],
    'isAvailable': true,
    'descFr': 'VTT 29 pouces à cadre aluminium hydroformé, transmission Shimano 21 vitesses et freins à disque.',
    'descEn': '29-inch hardtail mountain bike with lightweight aluminum frame, 21-speed Shimano gears, and disc brakes.',
  },
  {
    'id': 'item_7',
    'name': 'Objectif 50mm f/1.4 Portrait',
    'nameFr': 'Objectif 50mm f/1.4 Portrait',
    'nameEn': '50mm f/1.4 Prime Portrait Lens',
    'category': 'PHOTO',
    'categoryFr': 'Photo & Vidéo',
    'categoryEn': 'Photography',
    'city': 'Lyon, France',
    'price': 35,
    'rating': 4.9,
    'reviews': 31,
    'color': const Color(0xFFF5F3FF),
    'icon': Icons.camera_outlined,
    'iconColor': const Color(0xFF7C3AED),
    'image': 'assets/images/lens.jpg',
    'images': [
      'assets/images/lens.jpg',
      'assets/images/lens2.jpg',
      'assets/images/lens3.jpg',
    ],
    'isAvailable': true,
    'descFr': 'Objectif à focale fixe ultra-lumineux à ouverture f/1.4 procurant un bokeh circulaire soyeux.',
    'descEn': 'Ultra-fast 50mm f/1.4 prime lens delivering smooth bokeh and exceptional low-light clarity.',
  },
  {
    'id': 'item_8',
    'name': 'Enceinte sono portable 500W Bluetooth',
    'nameFr': 'Enceinte sono portable 500W Bluetooth',
    'nameEn': '500W Portable Bluetooth Sound System',
    'category': 'AUDIO',
    'categoryFr': 'Audio',
    'categoryEn': 'Audio',
    'city': 'Paris, France',
    'price': 35,
    'rating': 4.8,
    'reviews': 20,
    'color': const Color(0xFFFDF2F8),
    'icon': Icons.speaker_outlined,
    'iconColor': const Color(0xFFDB2777),
    'image': 'assets/images/speaker.jpg',
    'images': [
      'assets/images/speaker.jpg',
      'assets/images/speaker2.jpg',
      'assets/images/speaker3.jpg',
    ],
    'isAvailable': true,
    'descFr': 'Système de sonorisation portable sur batterie avec 2 micros HF sans fil et égaliseur stéréo.',
    'descEn': 'Battery-powered 500W PA sound system with dual wireless UHF microphones and built-in EQ.',
  },
];
